### ISSUE TITLE
'.history' is covered by 'target'

### ISSUE THREAD

**Issue by kukido** [hsz/idea-gitignore#118]
The plugin reports that '.history' is covered by 'target'. I don't see why would it do that. I'm using version 1.1.1

![screen shot 2015-05-01 at 6 53 20 am](https://cloud.githubusercontent.com/assets/1329454/7431024/222e512c-efcf-11e4-8ef6-ee332dc2f431.png)

**Comment by hsz** [comment]
@kukido Thank you for reporting.

It looks like that somewhere in the `target` directory there is also `.history` file. If it doesn't appear anywhere else then `.history` rule is covered by the `target` rule.

**Comment by qzole** [comment]
I see this as an issue.
Just because currently all the `.history` files are under the `target` directory, it does not mean they will always be only there.
To put here my example, the java and Maven templates generate such a warning too, since all the `*.class` files are under the `target` directory (if the project is compiled with maven), but of course that doesn't rule out that `*.class` files can't pop up elsewhere.
Is there a reason that coverage is checked this way instead of checking the regular/glob expressions themselves?

**Comment by hsz** [comment]
@qzole 

> Just because currently all the `.history` files are under the `target` directory, it does not mean they will always be only there.

That's not the reason. If `target` rule matches the set which contains a subset matched by another `*.class` rule - it's obvious that ignore rules can be simplified.

Those inspection is run for the current project state and will not predict that `*.class` files can appear anywhere else.

You can disable this inspection in the project settings or just ignore it.
