### ISSUE TITLE
Double star pattern /** doesn't gray out files in subdirectories

### ISSUE THREAD

**Issue by thasmo** [hsz/idea-gitignore#165]
When using an ignore rule like `/public/**` Git will ignore **all** files within the public directory **and** all subdirectories. idea-gitignore does **not** match files within subdirectories and so it doesn't mark them in the project file-tree as ignored, visually.

In other words, when using `/public/**` in the .gitignore file, idea-gitignore will **not** gray out files within `/public/static/` in the project file-tree.

**Comment by hsz** [comment]
@thasmo Thank you for your bug report.

In fact I cannot reproduce this issue:

Not grayed - because of no rules - it's fine.
![image](https://cloud.githubusercontent.com/assets/108333/11059852/77a925b8-879c-11e5-885f-90d2f12c5837.png)

Uncommented `/public/**` rule grays out the proper content:
![image](https://cloud.githubusercontent.com/assets/108333/11059866/99f4db26-879c-11e5-8557-a610aba49d88.png)

Can you verify it again ?
What versions of IDE / plugin do you use ?

**Comment by hsz** [comment]
@thasmo Can you verify it with the latest `v1.3.3` version ?

**Comment by thasmo** [comment]
@hsz, it works for me with PhpStorm 2016.1. Later I will check at home with IntelliJ IDEA 2016.1.

**Comment by thasmo** [comment]
@hsz, looks fine with IntelliJ IDEA 2016.1 too.

**Comment by thasmo** [comment]
Thanks for fixing and thanks for developing this great plugin! :+1:

**Comment by Alexsey** [comment]
Same problem with 1.7.5 and WebStorm 2016.3.3. In one of my projects it's even looks like this:
![ignore_bug](https://cloud.githubusercontent.com/assets/6392013/23315846/a9269d7a-fad0-11e6-919d-c5a9324f4d53.png)
Two folders where one looks like existing, and one looks like it's not.

**Comment by Alexsey** [comment]
Would you reopen this bug, or should I file a new one?

**Comment by forresthopkinsa** [comment]
I'm also having this bug in IDEA 2017.2.6.

```
*
!src/**
```

*However*, if I replace `!src/**` with `!src/**/**`, it seems to work...
