### ISSUE TITLE
Color coding not working with ! syntax..??

### ISSUE THREAD

**Issue by angelleye** [hsz/idea-gitignore#188]
I'm using this .gitignore content...

```
*
!**/
!.gitignore
!README.rst
!instructions.html
!application/controllers/paypal/*
```

It's lighting up the files under root showing that they are getting tracked, but the stuff under application/controllers/paypal/ is still grayed out even though it is indeed tracking.

![image](https://cloud.githubusercontent.com/assets/629241/12671309/43f7b776-c634-11e5-89e9-63ecdb3f3d37.png)

**Comment by hsz** [comment]
@angelleye Sorry, but it doesn't look like a bug. Let me describe you a scenario with excluding in gitignore files:

Let's assume following tree:

    .
    ├── dir
    │   ├── a.txt
    │   └── b.txt
    └── foo.txt

If you create rule:

    *

All files will be ignored. There is no absolute path (like `/*`) so ann files in subdirectories match this rule. So:

    *
    !dir

will exclude directory but all files in it will be still ignored:

    $  git ls-files --others --ignored --exclude-standard
    dir/a.txt
    dir/b.txt
    foo.txt

With rule:

    /*
    !dir

`dir` will be excluded:

    $  git ls-files --others --ignored --exclude-standard
    foo.txt

Also following rule:

    dir
    !dir/a.txt

will not exclude `a.txt` because `dir` matches the parent directory:

    $  git ls-files --others --ignored --exclude-standard
    dir/a.txt
    dir/b.txt

but this one will work:

    dir/*
    !dir/a.txt
    
    $  git ls-files --others --ignored --exclude-standard
    dir/b.txt

**Comment by angelleye** [comment]
Ok, thanks for the detail.  I wound up just ignoring everything I didn't want instead of trying it this way, but I will play around with this.  Thanks again!
