### ISSUE TITLE
JetBrains template does not include *.iml entry

### ISSUE THREAD

**Issue by bamapookie** [hsz/idea-gitignore#235]
My module config file moduleName.iml is not being ignored after adding the JetBrains template.

**Comment by lingsamuel** [comment]
And the whole .idea/ directory.

**Comment by hsz** [comment]
@bamapookie @lingsamuel 

All templates are periodically fetched from the https://github.com/github/gitignore/ repository. JetBrains template is located here: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

As you can see, the `*.iml` rule is not present - it was removed from the template.
The same thing about `.idea/` directory entry.

Since we depend on the GitHub's repository, the only thing to fix that is creating new `user's template` and define all mising rules by your own.

**Comment by bamapookie** [comment]
Thanks.  I reviewed the recommendations from JetBrains, and it should not be in the gitignore file.  That particular file does not contain user-specific settings anymore (if it ever did).
