### ISSUE TITLE
CVS .ignore definitions are recursive

### ISSUE THREAD

**Issue by Riekr** [hsz/idea-gitignore#274]
If I put *.txt in module root folder .ignore file all .txt files are shown as ignored in subdirectories too, when changing one of those files the correctly appear in the "Local Changes" tab.

**Comment by hsz** [comment]
@Riekr Thank you for this report.

That happens because you had tracked already all the `*.txt` files and added this exclusion _at the end_.
If you'll create new `foo.txt` within your project, it will not be added to the repository.

With the newest `v1.7` release there will be an option to _untrack_ newly ignored files (it will perform `git rm --cached filename.txt` action).

**Comment by Riekr** [comment]
Sorry,
 i've not been clear I think.
Given the structure:
```
\foo\bar.txt (shown as ignored but taken into account in local changes tab)
|.cvsignore
|ignore1.txt (really ignored)
|ignore2.txt (really ignored)
```
where `.cvsignore` contains `*.txt` all .txt files gets respesented as ignored even `bar.txt` which is in a subfolder, only `ignore?.txt` are really ignored as they never appear as modified in the local chages tab.
It's most a cosmetic issue happening with CVS, i've not tried with other version controls.

**Comment by Riekr** [comment]
I can confirm this issue is still present in 1.7.3

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by Riekr** [comment]
sorry, we stopped using cvs since last May
