### ISSUE TITLE
Frequency of releases

### ISSUE THREAD

**Issue by linusnorton** [hsz/idea-gitignore#314]
Could you possibly release less frequently? There have been about 5 releases in the last week and I have to restart idea every time.

**Comment by hsz** [comment]
@linusnorton 

If you are annoyed of the updates frequency last days - you don't have to update it.
But be aware that you'll face some issues that were fixed.

I can postpone releases but instead of getting an update notification you will get 10 error notifications instead.

Those hot fixes releases is nothing that I'd expect and it's not my habbit to run _PUBLISH_ task with the breakfast.

Also - everytime I got a report about something that should be fixed ASAP - I removed this update from the public channel, but JetBrains introduced _moderator confirmation_ feature - and I have to wait for their guys to confirm my operation (what didn't happen during the weekend). So that's why you got plenty of version instead of one fully fixed.

![image](https://cloud.githubusercontent.com/assets/108333/22925818/67c6f330-f2aa-11e6-9f24-4ec40b4b85fa.png)

So please understand my situation because I don't receive any regular payment from anyone for this plugin - and I'm still trying to deliver all the best I can do for you. Sometimes bug happens, sorry for that.

**Comment by linusnorton** [comment]
No problem at all, I don't want to come across as pushy, you guys are writing code I'm using for free and I appreciate it. But, I thought I should make you aware it's been quite noticeable.

If there were critical bugs that needed fixes then that's all that needs to be said really. I'm glad it's not some new form of continuous delivery to plugins with every minor change.

**Comment by hsz** [comment]
I'm totally aware that every time I release something - it's shown to the people in number ~400-600k.

On [/releases](https://github.com/hsz/idea-gitignore/releases) page you can see that previous versions (except this 1.7.x hot fixes) were delivered in bigger packages (features+fixes) much less often:

![image](https://cloud.githubusercontent.com/assets/108333/22926462/f0eb6ac2-f2ac-11e6-8578-9c4707a93bd0.png)

**Comment by malikoth** [comment]
Dealing with a never-ending stream of software updates is something we all have to deal with on a daily basis with our phones, our desktops, our laptops, our servers, our Raspberry Pis running our weekend hacking projects, etc.  We know that it's an annoyance, but in no scenario is "Withhold releasing better code" a valid solution to the problem.  Choosing not to update your installed software is a much better solution.  I know we like to stay up to date so that things don't nag us for updates, but I'd rather have the choice to stay up to date with the latest features and most stable build available.  Spending 30s restarting PyCharm, even if it happened once every single day, would be a small price to pay.  Thanks for what you do, @hsz !
