### ISSUE TITLE
.dockerignore file will not open in PHPStorm and icon has ?

### ISSUE THREAD

**Issue by StevenWillett** [hsz/idea-gitignore#376]
**Issue:**
.dockerignore files created using the .ignore plugin show in the tree but the icon firstly shows a file with a overlaying question mark (?), each time i try to open the .dockerignore file generated i just get a flashing loading icon with no result.
Screen grab of issue: https://youtu.be/Sd2RVIfr2Bc

**Platform:**
Edition: Windows 10 Pro
Version: 1607
OS Build: 14393.1358

**IDE:** 
PhpStorm 2016.3.3
Build #PS-163.13906.21, built on March 8, 2017

**Steps taken:**
1) Checked .ignore plugin for updates (up to date)
2) Checked IDE for updates (up to date)
3) Manually updated .ignore plugin to Version: 2.0.0-rc.1 (Same issues)
4) Checked for windows updates (up to date)
5) Restarted machine & all applications fully.

**How to replicate**
1) Install .ignore plugin
2) Right click on project tree root directory > New > .ignore file > select ".dockerignorefile (Docker)"
3) Check icon of newly created .dockerignore file to see if you get file icon with a question mark (?) or correct docker icon.
4) Try to open .dockerignore file in PHPStorm IDE without a flashing loading icon.
5) Confirm if file opens in the IDE (Mine do not ever open in PHP Storm) (I can open in another IDE i.e. Brackets, so ruling out corrupt file in my eyes.)

**Comment by hsz** [comment]
@StevenWillett Thank you for this report. As we can see in the Project View - _.dockerignore_ file has a default IDE iconf for not recognized types (file icon with question mark).

Can you please check if in settings: `Settings > Editor > File Types` you have `.dockerignore` entry under the `Docker` group (the one with gray icon - I bet you have two Docker groups because of its plugin installed):

![image](https://user-images.githubusercontent.com/108333/27622578-3df02c06-5bd8-11e7-98b1-d34e8dade86d.png)

**Comment by StevenWillett** [comment]
@hsz See attached, I cannot see .dockerignore in my recognised file types list which would explain the icon issue.

![ide file types](https://user-images.githubusercontent.com/10869028/27710704-8c2b3190-5d18-11e7-97cd-795d18d2f621.PNG)

**Comment by hsz** [comment]
It should be fixed with #375 in the newest release.
