### ISSUE TITLE
Does not report "ignored-but-still-tracked" any more

### ISSUE THREAD

**Issue by oli-h** [hsz/idea-gitignore#455]
### Prerequisites
Have a project with **a file being tracked** by Git.
Then add **this file** to .gitignore and commit this stuff
Import this project in IntelliJ

### Description
Former versions of this gitignore plugin reported such "tracked-but-in-gitignore" files on IntelliJ startup.
The current version doesn't do this any more.

I can't say if this is now a bug - or it's just a removed feature.

**Comment by kasperpeulen** [comment]
Yes, I miss this feature.

I think it is a bug, because the untrack ignored files dialog gives empty result.

![image](https://user-images.githubusercontent.com/1035299/30103292-7536b742-92f2-11e7-9b3f-e04abcfa61cb.png)

![image](https://user-images.githubusercontent.com/1035299/30103319-9146447a-92f2-11e7-88eb-4df4fbad6bef.png)

**Comment by hsz** [comment]
Fix has been published with `v2.2.2`.

**Comment by oli-h** [comment]
Thx @hsz for all your work
