### ISSUE TITLE
The following plugins are incompatible with the current IDE build: .ignore

### ISSUE THREAD

**Issue by ki773n** [hsz/idea-gitignore#496]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

I am using the following intellij version

> IntelliJ IDEA 2017.2.6
> Build #IC-172.4574.11, built on November 13, 2017
> JRE: 1.8.0_152-release-915-b10 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Win 10 1607 OS 14393.1884

Plugin Error notification on launch.  I was hoping there may be a pending plugin update?

**Comment by hsz** [comment]
@ki773n Thanks for this update.

Previous version in v2.3.0 has been blocked by JetBrains because of some critical issue for some of their users.
I have released fixed version v2.3.2 but it's still waiting for their tests and approve.

> The plugin update is pending JetBrains approval

https://plugins.jetbrains.com/plugin/7495--ignore

This issue is available anyway in the (releases)[https://github.com/hsz/idea-gitignore/releases/latest] section for manual installation.

**Comment by hsz** [comment]
@ki773n New version has been released to the plugins repository and approved by JetBrains team.
Everything should return to normal.

**Comment by petergloor** [comment]
This also solved an issue I experienced with the latest version of Golang. However, a manual update was required.

GoLand (1.0 Preview) 1.0 EAP
Build #GO-173.3727.79, built on November 21, 2017
GoLand EAP User
Expiration date: December 21, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by hsz** [comment]
@petergloor This manual instalation was required because of locked plugin in plugins repository by JetBrains - now they have released it so it should be available again for auto update.
