### ISSUE TITLE
Support Google Cloud Ignore files “.gcloudignore”

### ISSUE THREAD

**Issue by slavaatsig** [hsz/idea-gitignore#577]
Basically, [.gcloudignore](https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore) is almost like `.gitignore` except it has a special comment that can include another `.gitignore`-like file (without recursion.)

**Comment by JasonTheAdams** [comment]
@hsz I'm currently having an issue with this marking files/directories as ignored in the file tree rather than reflecting the VCS. In the screenshot below the tests directory, for example, is tracked by git, but after adding the .gcloudignore file (which does ignore it) the directory was marked as ignored.

![File tree with wrong files ignored](https://cl.ly/495e61159437/Image%2525202019-04-30%252520at%2525208.42.37%252520AM.png)

Thanks for this great plugin!

**Comment by JasonTheAdams** [comment]
@hsz Just updated to 3.1 and the problem persists, I'm afraid.

**Comment by hsz** [comment]
@JasonTheAdams Recently you've marked `.gcloudignore` as a `Git` type, so it was treated as a VCS-type, so it was coloring the Project Tree.
Now it is handled separately as `Google Cloud`, so it's possible to uncheck the _Enable ignoring_ in the plugin's settings:

![image](https://user-images.githubusercontent.com/108333/57350323-f5b9c300-715d-11e9-90e1-0f1b6b8d2d0b.png)

**Comment by JasonTheAdams** [comment]
@hsz Thank you for pointing that out. I actually found that a day or two ago, but unfortunately it hasn't resolved the issue. Google Cloud does currently have the "Enable ignoring" unchecked:
