### ISSUE TITLE
Add listing of the program of MySQLWorkbench

### ISSUE THREAD

**Issue by CoHyper** [hsz/idea-gitignore#74]
In my project I use MySQLWorkbench and save the file "table.mwb" in the GIT. The file "table.mwb.bak" is just a local backup and can be added to gitignore.

```
### MySQLWorkbench template
*.mwb.bak
```

INFO: The extension "* .bak" is already used e.g. in "Eclipse template".

**Comment by hsz** [comment]
@CoHyper Thank you for your post.

Every template delivered with this plugin comes from https://github.com/github/gitignore repository.
Users takes care of the most common patterns and popular languages/IDE/environments.
That's why I do not provide any other templates than those from above repo.

In <kbd>Settings</kbd> > <kbd>Ignore files support</kbd> there is available an option to add your own polished `User templates` and reuse them in the feature.

I believe it'll fit your needs.

Good luck in your work !
