### ISSUE TITLE
Does using this plugin cause gitignored files to be excluded from indexing?

### ISSUE THREAD

**Issue by joshk0** [hsz/idea-gitignore#78]
Hi there,
Sorry to use a github issue to ask this silly question, but does this project cause the files that are gitignored to be excluded from IDEA's indexing?
This feature would be very important for us and would reduce the need for us to repeat the ignores in our *.iml files.
Thank you for what looks to be a well supported project!
-Josh

**Comment by hsz** [comment]
Hello @joshk0 

Ignore rules do not affect the IntelliJ project/module settings and it will not exclude files from the project.
If some file is excluded (an `excludeFolder` entry is described in *.iml file) - I have no access to it. 
For example I cannot navigate user to the file with <kbd>Ctrl</kbd> + <kbd>Left click</kbd> or cannot suggest filename and it does not appear in the *Project View* - because of IntelliJ API.

Anyway - I'll try to investigate it more to check if it's possible to exclude files from idexing during the runtime without excluding from the project. I'll let you know here if it'll be available to implement.

**Comment by joshk0** [comment]
Cool. It'd be good enough, I think, if the plugin was able to sync gitignored entries to project level exclusions. Thanks for the reply.

**Comment by hsz** [comment]
After 2 years of dealing with IntelliJ SDK I can confirm that it's not possible. :(
