### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by infostreams** [hsz/idea-gitignore#91]
Hi! 

I love your plugin, but can I ask you to take into consideration that every time you push a new release, I am asked to update and restart.... That's ok, but it seems to happen really quite regularly these days and I'm a bit fed up with it. In the future, would it be possible to combine multiple minor things into one bigger release once a month, for example? Because every time you tag and push, I (and many others) have to update and restart. Not a problem if it doesn't happen every other day, but can we at least agree that 5 updates a month are a bit too much?

Thanks!
Ed

**Comment by agileinsider** [comment]
I have to completely agree...

**Comment by hsz** [comment]
Hello Ed and Mark !

Sure, there are many updates of the plugin (2 in Feb and next 2 in Mar).

I do not push new release with every commit - it always contains something more important than typos.

According to the https://github.com/hsz/idea-gitignore/releases page:

| Release | Commits amount | Release date |
| ---------- | ---------------------- | ----------------- |
| **1.0.2** | 15 | 4 Mar |
| **1.0** | 37 | 2 Mar |
| **0.9** | 13 | 19 Feb |
| **0.8.1** | 6 | 4 Feb |
| **0.8** | 26 | 22 Dec |

Minor versions are released always when I do some bugixes for plugin or IDE crashes.

In my opinion you are overreacting because every update is delivering better software and costs you only IDE restart at the end or beggining of the day (5 this year, not month).

Remember that you always can skip update of the plugin and wait for a month until updating because I will not do some fake delays between releases.

Thank you very much for your opinion !

Jakub

**Comment by infostreams** [comment]
First of all, thanks for the work. I don't want to come across ungrateful. You did forget v1.0.1, so we did have 5 releases this month. I am going to uninstall your plugin and install it from disk, which will hopefully prevent the auto-update. I have over 40 plugins installed and none of them updates as much as yours – and I'm not the only one who's annoyed with it. What you do with that information is yours to decide. Many thanks again,
Ed

**Comment by renestalder** [comment]
Came here to create a thread about the same topic. So I'm absolutely with @infostreams. Constant updates are okay, but it gets really annoying when the update popup comes up everytime I start an Idea Editor. And I mostly using Webstorm and PhpStorm both, so I update twice everytime.

I have no idea how difficult or easy it is to test Idea plugins to make sure, it works on all platforms. In my projects, we are not pushing out a release for every fix. This only happens if it's a bug breaking things for a major group of users and if this happens, somebody in our team didn't test good enough. Else, we also stick to release cycles for patches (which are a week in minimum).

I do not say it's your fault for serving bug fixes and maintain the plugin. Idea could handle the whole update thing a lot easier e.g. with update in background options, that's how Sublime Text is doing it. As long this is not possible, every update of plugin is also some kind of annoying and I think, idea plugin developers should keep that in mind.

Thanks for your effort.

**Comment by hsz** [comment]
@infostreams 

Release `v1.0.1` was ommited in this table because of `v1.0.2` hotfix and hit only 896 downloads (for now `1.0.2` has over 10k downloads).

Installing plugin from disk will not prevent you from receiving update information.

@renestalder 

Thank you for joining. 
Testing of the plugin requires manual installing plugin on all IDE instances in various builds and types and click around. In example yesterday issue #84 affected only the CLion IDE - it was working on IDEA12-14 and PhpStorm, Android Studio and others - it does not take 30 minutes.
Anyway there is also Travis running for every pushed commits but it tests only building and written test cases.

**Comment by 76200** [comment]
@infostreams, @agileinsider, @renestalder I don't get you guys. You don't have to update your plugins each time new version comes out. You can simply ignore it. Those 2 releases contains fixes for critical issues, so I think there's no need to exaggerate ;)

**Comment by infostreams** [comment]
Thanks for the info. What would I need to do to switch off receiving the update information? Would renaming the plugin help? I searched for an update-url in the code but I couldn't find it.

Regardless, I'm of the opinion that you shouldn't push out updates and force everyone to restart if the bugfix only affects a small part of your user base. I saw that this plugin has over 1 million downloads (congrats!). With your current policy you are forcing everyone to restart, just because you fixed a minor issue for one guy in CLion. As an alternative, consider something along the lines of what @renestalder proposed: only push out a hotfix update if it is critical that *all* users update, and otherwise just release once a month. You can send the person who filed the bugfix a .jar file to solve his immediate issue.

**Comment by infostreams** [comment]
@76200 The issue is that the update will show up every day until I accept it. Obviously I can ignore it every day, and I have, but I'd rather not be asked at all – especially not if it's for a minor issue that doesn't concern me. It's like one of those annoying Windows popups that say that yet another Java update is available. Just google to see if I'm the only one who doesn't like those.

**Comment by hsz** [comment]
@infostreams 

1M of downloads is a total count for all releases. There is something about 200k real users. Anyway when I release `x.y` and it's downloaded by 10k users and after that I do some quickfix with `x.z` release - only those 10k users has to update it again and other 190k will get only one (latest update). That's why I'm trying to fix everything ASAP if there is some serious trouble with the plugin.

About updating process - I push releases to the JetBrains repository - there is no URL to the package and IDE checks periodically if there is any update. Also you can dismiss the update in the IDE - that's the only way to ignore the minor releases.

About the IDE restart requirement - it's the IDE policy, not mine. IDE asks you to restart because it's Java application and has to reload all of the classes.

Sublime has other plugins management system so it allows to not reload whole IDE when updating.

About CLion issue - it totally crashed application - I cannot let CLion users to meet the bug because few of users is annoyed with the update. Sorry.
And the thing about sending jar file - come on, seriously ?

Not wanting to be malignant - prepare yourself for `v1.0.3` soon.
But now you can be sure there will be a longer delay because every (known) issue has been fixed and I have to focus on other project.

**Comment by infostreams** [comment]
Ok. I am curious to see if I'm offered the update (since I installed from disk). I'll let you know here how that goes. You can close the issue as far as I'm concerned.

**Comment by hsz** [comment]
You will be noticed for sure because of incremented version.
Some solution for you (because I don't know if others want to disable updates too) is installing plugin with higher version number.

Edit jar package and change

    <version>1.0.2</version>

to

    <version>1.0.999</version>

in file:

    /META-INF/plugin.xml

**Comment by infostreams** [comment]
Ok, thanks! I'll try that.

**Comment by johnwheeler** [comment]
Just uninstalled this plugin because of this issue, fyi. Functionality is not that important and telling multiple people they're overreacting because they're annoyed they have to restart is not their usability error -- it's yours.

**Comment by hsz** [comment]
@johnwheeler Restarting IDE is forced by the JetBrains - always after upgrading any plugin.

If you require upgrading plugin without your knowledge - use Sublime Text, not JetBrains software.
As I said - I will not wait few months to release new feature or fix because of your shitstorm.

**Comment by agileinsider** [comment]
@hsz You're **arrogance is astounding** - so much so I've happily uninstalled your plugin - it's not exactly rocket science to edit a .gitignore file (particularly since the *templates are freely available* at https://github.com/github/gitignore), and I wouldn't want to turn off minor updates of "useful" plugins simply because you have issues maintaining a simple text file.  
**Simple solution - UNINSTALL...**

**Comment by hsz** [comment]
@agileinsider Don't tell me about the arrogance - you are complaining about something that is useless for you. Isn't it funny ?
I don't force you to use it - you've installed it because you wanted. Uninstall it if it does not fit your needs and please do not yell around because it is not just like you would it be.

**Comment by renestalder** [comment]
@76200 of course I'm not forced. The update message is there anyway and I can't prevent it and I should have to just because one plugin is going crazy. So my question may better be, why is there a critical update and 10 hours later another critical update? Also a patch should be testet. Even more important if you push updates to 200k users. So it looks something have got wrong. Which isn't fatal in that case, but a sign of that "we should take care if we push updates to 200k users". In this moment it sounds more like "this plugin could possibility crash my IDEs with every update" and the release policy sounds like "try and error". That makes it a little bit unconfident.

@johnwheeler he can't change how Jetbrains or Java handles updates. So no, it's not his fault.

@hsz Thanks for the insight of the downloads. I would have done it the same as you in this case. Anyway, as said, you should be careful when pushing to 200k users. I would help to test new releases, but unfortunately I'm just on OSX at this time. And better not argue with people who do not deliver constructive inputs. Better ignore.

**Comment by hsz** [comment]
@renestalder Thank you for your comment. You're right.

About the critical issue - I was doing it one by one because as I wrote before - just less than 1K people downloaded failed release (plugin was failing only on CLion which is not so popular yet). So just 1K people had to update it again few hours later. I think it's not so high price.
200K users amount is gained after a few weeks - so time matters when there is a fix to do.
